(* ::Package:: *)

(* ::Input:: *)
(*(*intestazioni*)*)
(*BeginPackage["Sudoku`"]*)
(*Sudoku::usage = "Sudoku[DIFFICULTY] crea un'istanza del gioco Sudoku con vari livelli di difficolt\[AGrave] selezionabile dal client ponendo DIFFICULTY='easy', 'medium', 'hard'"*)
(*Power::usage=*)
(*"Funzione di test"*)
(*(*Se creiamo altre funzioni da usare nel pacchetto vanno descritte qui*)*)
(**)
(*Begin["`Private`"]*)
(*(* DIRETTIVE*)
(*Inserire nella prima coppia di graffe tutte le variabili che usiamo nel codice. TUTTE. Inserire all'interno delle seconde graffe il codice vero e proprio*)
(**)*)
(*Sudoku[x_] := Module[{}, {}]*)
(*Power[x_, n_]:= Module[{i}, Sum[x^i, {i, 1, n}]]*)
(**)
(*End[]*)
(*EndPackage[]*)
